#!/usr/bin/env bash

echo "Iniciando instalação..."

if [ ! -d ~/.local/share/nvim/site/pack/packer ]
then
  git clone https://github.com/wbthomason/packer.nvim \
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim
fi

nvim --headless  -c "autocmd User PackerComplete quitall" -c "PackerSync"
echo "Packer instalado!"
