#!/usr/bin/env bash

echo "Iniciando instalação..."

if [ ! -d ~/.local/share/nvim/site/pack/packer ]; then
  git clone https://github.com/wbthomason/packer.nvim \
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim
fi
echo "Packer instalado!"

# Instala todos os plugins
nvim +PackerInstall
