# -- ZSHRC --------------------------------------------------------------------

source "$ZDOTDIR/functions.zsh"

zsh_add_file "$ZSH/oh-my-zsh.sh"

zsh_add_file "$ZDOTDIR/aliases.zsh"
zsh_add_file "$ZDOTDIR/key-bindings.zsh"

zsh_add_file "$HOME/Dropbox/dotfiles/secrets"
zsh_add_file "$HOME/Dropbox/dotfiles/aliases.zsh"

# -- Plugins -------------------------------------------------------------------

zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zdharma/fast-syntax-highlighting"

# -- Plugin Preferences --------------------------------------------------------

# Autosuggestions
bindkey "^ " autosuggest-accept

# -- Fzf -----------------------------------------------------------------------

zsh_add_file "$XDG_CONFIG_HOME/fzf/fzf.zsh"

# -- Rustup --------------------------------------------------------------------

zsh_add_file "$XDG_DATA_HOME/cargo/env"

# -- Zoxide --------------------------------------------------------------------

eval "$(zoxide init --cmd j zsh)"

# -- Starship ------------------------------------------------------------------

eval "$(starship init zsh)"
