#!/usr/bin/env bash

load_themes() {
  python3 "$XDG_CONFIG_HOME/terminal/config.py" "load"
}

set_theme() {
  theme_file=$(python3 "$XDG_CONFIG_HOME/terminal/config.py" "set")
  zsh_add_file "$XDG_CONFIG_HOME/terminal/colors/$theme_file"
}

if [ ! -e "$TERMINAL_THEME" ]
then
  theme=$(grep -n1 BEGIN "$XDG_CONFIG_HOME/kitty/kitty.conf" | tail -n1 | cut -d '#' -f2)
  THEME=${theme:1}
  TERMINAL_THEME=$(printf %s "${THEME}" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')
  export TERMINAL_THEME
fi

zsh_add_file "${XDG_CONFIG_HOME}/terminal/colors/${TERMINAL_THEME}"
