#!/usr/bin/env bash

HANDBOOK="$(xdg-user-dir DOCUMENTS)/handbook/"

tmux-window() {
  # tmux new-window -n "$(basename "$0")" "$SHELL" -c "$1"
  tmux new-window -n "$(basename "$0")" "$SHELL" -c "$1 | glow - -s dracula"
}

open_handbook() {
  selected=$(find "$HANDBOOK" -maxdepth 1 -type f \
    ! \( -name "README.md" -o -name "LICENSE" \) |\
    fzf -e -i --delimiter '/' --with-nth '-1' --prompt="Handbook: ")

  if [ -n "$selected" ]; then
    tmux-window "$(realpath "$0") $selected"
  fi
}

main() {
  if [ -z "$1" ]; then
    open_handbook
  else
    # Open on readonly mode and close just pressing `q`
    # nvim -R "$1" -c "lua vim.keymap.set('n', 'q', '<cmd>:q<cr>')"
    cat "$1"
  fi
}

main "$@"
