#!/usr/bin/env bash

HEADER_LEN=1

header() {
  head -$HEADER_LEN "$1"
}

show() {
  syntax=$(header "$1" | grep "syntax" | cut -d : -f2 | tr -d '[:space:]')
  if [ -n "$syntax" ]; then
    bat "$1" -l "$syntax" -r $((HEADER_LEN + 1)):
  else
    bat "$1" -l "sh"
  fi
}

show "$1"
