#!/usr/bin/env bash

URL="https://github.com/ogham/exa/releases"
RELEASES="$URL/latest"
DOWNLOAD="$URL/download"

LATEST=$(curl -s $RELEASES | cut -d'"' -f2)
VERSION=$(basename "$LATEST")

ARCH="linux-x86_64"
AMD64_ZIP="exa-${ARCH}-${VERSION}.zip"

pushd "$(mktemp -d)" &>/dev/null || exit 1

curl -L "$DOWNLOAD/$VERSION/$AMD64_ZIP" -o "$AMD64_ZIP"

unzip "$AMD64_ZIP"

sudo mv man/exa.1 /usr/share/man/man1
sudo mv bin/exa /usr/local/bin
sudo mv completions/exa.zsh /usr/local/share/site-functions

popd &>/dev/null || exit 1
