#!/usr/bin/env bash

make_dir() {
  [ ! -d "$1" ] && mkdir -p "$1"
}

BIN_DIR="$HOME/.local/bin"
APPS_DIR="$HOME/.local/share/applications/"

# Install pre-built binary
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

# Create a symbolic link to add kitty to PATH
make_dir "$BIN_DIR"
ln -s ~/.local/kitty.app/bin/kitty "$BIN_DIR"

# Place the kitty.desktop file somewhere it can be found by the OS
make_dir "$APPS_DIR"
cp ~/.local/kitty.app/share/applications/kitty.desktop "$APPS_DIR"

# Update the path to the kitty icon in the kitty.desktop file
sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" \
  "${APPS_DIR}/kitty.desktop"
