#!/usr/bin/env bash

URL="https://github.com/sharkdp/bat/releases"
RELEASES="$URL/latest"
DOWNLOAD="$URL/download"

LATEST=$(curl -s $RELEASES | cut -d'"' -f2)
VERSION=$(echo "$LATEST" | awk -F "v" '{ print $NF }' | cut -d'"' -f1)

ARCH="_amd64"
DEB_AMD64="bat_$VERSION$ARCH.deb"

cd "$(mktemp -d)" || exit 1
curl -L "$DOWNLOAD/v$VERSION/$DEB_AMD64" -o "$DEB_AMD64"
sudo dpkg -i "$DEB_AMD64"
cd - || exit 1
